apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: ramesh
spec:
  groups:
  - system:authenticated
  request: ${BASE64_CSR} 
  usages:
  - digital signature
  - key encipherment
  - client auth
